### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by dikaio** [seaneking/svelte-imgix#2]
Hi Sean. I'm attempting to use your package in a Sapper project but Sappers having trouble finding the module. The error shows that it's looking in `node_modules/svelte-imgix/src/index.js` but the actually package is being installed at `node_modules/svelte-imgix/dist/index.js` compiled.

First time I've run into this, reading some other svelte issues this looks like it's the way that Sapper needs to have the entire component uncompiled. Is there a quick fix to this?

**Comment by schnubor** [comment]
Same issue here, currently unusable.

**Comment by dikaio** [comment]
Hi @schnubor. Actually I am using svelte-image in a couple other projects, the one Im working on now is a migration from another framework and they already have imgix setup so I'm a little bound to the requirements. Love svelte-image though.

I think I'll just tie it all in with imigix docs.

**Comment by seaneking** [comment]
Sorry guys forgot to include `src` in the NPM package when I refactored `svelte-imgix` for proper typescript definitions. Fixed in `v0.2.6`

**Comment by dikaio** [comment]
Swwet thanks @madeleineostoja!
